Repository seohyeonKK/DBproject, pull requests merged in 2020-06, with the labels that each got.

#2 DB와의 연동 성공
  dbconn.php
  index.html
  login.php
Labels: bug, enhancement

#8 로그인 최종 오류 수정
  index.html
  login.php
  login_check.php
  logout.php
  main.php
Labels: bug

#10 파일 삭제 및 중복 수정
  join.php
  아캔두잇/join.php
Labels: bug

#12 메인 페이지 수정 및 사건 정보 등록 페이지 추가
  insert.php
  login_check.php
  main.php
  register.php
Labels: enhancement

#14 DB에 입력받은 것을 등록
  insert.php
  logout.php
  main.php
  mypage.php
  register.php
Labels: enhancement

#16 사기 이력 조회 페이지 추가
  find.php
  insert.php
  join_form.php
  main.php
  mypage.php
  register.php
Labels: enhancement

#17 특정 계좌의 사기 내역 조회하는 페이지 생성
  find.php
  find_list.php
Labels: enhancement

#18 등록한 내역을 자세하게 조회 가능
  find.php
  find_list.php
  insert.php
  join.php
  join_form.php
  login.php
  login_check.php
  register.php
Labels: bug, enhancement

#19 등록한 정보의 품목과 가격을 조회함
  delete.php
Labels: enhancement

#20 삭제할 때 모든 정보를 출력
  delete.php
Labels: enhancement

#21 등록된 정보의 삭제를 위한 체크된 정보 전달
  delete.php
  delete_check.php
Labels: enhancement

#22 삭제 기능 구현
  delete.php
  delete_check.php
  find_list.php
Labels: bug, enhancement

#23 삭제 시 오류 수정, 조회 수정
  delete.php
  delete_check.php
  find_list.php
Labels: bug, enhancement

#24 회원정보 변경 가능하도록 수정
  change_name.php
  change_password.php
  join.php
  join_form.php
  login_check.php
  main.php
  mypage.php
  mypage_info.php
  name.php
  password.php
  register.php
Labels: enhancement

#26 웹페이지의 상세 디자인을 수정
  common.css
  delete.php
  find.php
  find_list.php
  index.html
  insert.php
  introduce.php
  main.php
  mypage.php
  mypage_info.php
  name.php
  password.php
  register.php
  user_information.php
Labels: enhancement

#27 예외처리 메시지 출력
  change_name.php
  change_password.php
  checkid.php
  delete.php
  delete_check.php
  find.php
  find_list.php
  insert.php
  join.php
  login_check.php
  main.php
  mypage.php
  mypage_info.php
Labels: bug

#28 디자인 수정 및 전체 조회 기능 추가
  allfind.php
  checkid.php
  common.css
  delete.php
  find.php
  find_list.php
  index.html
  insert.php
  introduce.php
  join_form.php
  main.php
  mypage.php
  register.php
  user_information.php
Labels: enhancement

#29 view 추가
  allfind.php
  delete.php
  delete_check.php
  find.php
  find_list.php
  insert.php
  introduce.php
Labels: enhancement

#30 추가 UI 수정
  allfind.php
  introduce.php
  join_form.php
  mypage_info.php
  password.php
Labels: enhancement

#31 질의문 수정
  delete.php
  delete_check.php
Labels: enhancement

#32 검거여부 삭제
  find_list.php
Labels: invalid

#33 로그인 세션의 값의 버그 수정
  user_information.php
Labels: bug

#34 사건 삭제 시 삭제가 안되는 오류 수정
  delete_check.php
Labels: bug

#35 입력폼 예외처리
  join_form.php
  register.php
Labels: enhancement

#36 코드에 주석 추가
  allfind.php
  change_name.php
  change_password.php
  checkid.php
  common.css
  dbconn.php
  delete.php
  delete_check.php
  find.php
  find_list.php
  index.html
  insert.php
  introduce.php
  join.php
  join_form.php
  login_check.php
  logout.php
  main.php
  name.php
  password.php
  register.php
  user_information.php
Labels: enhancement

#37 사기 등록번호 보이게 수정
  allfind.php
  delete.php
  find.php
  find_list.php
  mypage.php
  mypage_info.php
  name.php
  password.php
  register.php
  user_information.php
Labels: bug, enhancement

#39 조회시 정렬 옵션 선택
  allfind.php
  allfind_price.php
  checkid.php
  join.php
  main.php
Labels: enhancement

#40 누락된 부분 수정
  register.php
Labels: bug

#41 계좌 조회 시 숫자 외의 문자 예외 처리
  common.css
  find.php
  find_list.php
  register.php
Labels: bug

#42 주석 수정
  allfind.php
  change_name.php
  change_password.php
  checkid.php
  dbconn.php
  delete.php
  delete_check.php
  find.php
  find_list.php
  index.html
  insert.php
  introduce.php
  join.php
  join_form.php
  login_check.php
  mypage.php
  mypage_info.php
  name.php
  password.php
  register.php
  user_information.php
Labels: documentation

#43 리드미 작성
  README.md
Labels: documentation

#44 Change db connect
  README.md
  dbconn.php
Labels: documentation

#45 데이터 파일 추가
  db_project_dump/(1)db_project_member_info.sql
  db_project_dump/(2)db_project_cheater_info.sql
  db_project_dump/(3)db_project_account_info.sql
  db_project_dump/(4)db_project_cheat_info.sql
  db_project_dump/(5)db_project_victim_info.sql
  db_project_dump/(6)db_project_site_info.sql
  db_project_dump/(7)db_project_routines.sql
Labels: documentation
